# fly.toml app configuration file generated for railstodolist on 2023-09-10T23:01:39+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "railstodolist"
primary_region = "lhr"
console_command = "/rails/bin/rails console"

[build]

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
